# Generated by Django 5.1.4 on 2024-12-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_application_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='max_compensation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='min_compensation',
        ),
        migrations.AddField(
            model_name='application',
            name='compensation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
