# Generated by Django 5.1.4 on 2024-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_remove_application_max_compensation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='application',
            name='remote',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
